### ISSUE TITLE
Feature Request: Portal Requires Users to Fill a Form & Logo Customization

### ISSUE THREAD

**Issue by nasirhafeez** [woodjme/unifi-hotspot#7]
Hi Jamie,

As discussed I'm working on a project in which it is required that users fill a form containing fields like Name, Email, Phone, ID, etc before they are allowed to use WiFi. This information will then be saved into an online database (like Google Sheets or SQL) after validation of fields filled by a user.

Also, another common feature required by users is to be able to change the background of portal page or add their company's logo to it.

Could you please consider adding these features to this project? They are very commonly required and would help many people.

**Comment by woodjme** [comment]
I'm going to start working on this, by default the project will assume you don't need this feature but will look for optional environment variables such as the driver for the database. 

Proposing that when a user authenticates we could write to Google Sheets, a SQL database or fire a webhook to be consumed by any third party service.

Will start with Google Sheets.

**Comment by nasirhafeez** [comment]
Good!

I had used [this ](https://www.twilio.com/blog/2017/03/google-spreadsheets-and-php.html) for Google Sheets integration on my portal.

**Comment by woodjme** [comment]
I feel like before any changes could be merged #14 needs to be complete to allow people to continue using this repo as before.

**Comment by nasirhafeez** [comment]
That is for a customized login page with logo etc?
