### ISSUE TITLE
npm error command sh -c husky on "sudo npm install --omit=dev"

### ISSUE THREAD

**Issue by kouok415** [woodjme/unifi-hotspot#74]
sudo npm install --omit=dev

> unifi-hotspot@3.0.3 prepare
> husky

sh: 1: husky: not found
npm error code 127
npm error path /var/www/html/unifi-hotspot
npm error command failed
npm error command sh -c husky

can't figure it out , please help

**Comment by woodjme** [comment]
Go with `sudo npm install --omit=dev --ignore-scripts`

I'll update the docs accordingly

**Comment by kouok415** [comment]
> Go with `sudo npm install --omit=dev --ignore-scripts`
> 
> I'll update the docs accordingly

It works, thank you!

**Comment by woodjme** [comment]
35fcf6b21f36e3c196b0e9aafd581cb18a8273bd
